[time]
disabled = false

[directory]
truncation_length = 100
truncate_to_repo = false

[character]
error_symbol = "ğŸ¥º"

[git_branch]
symbol = "ğŸŒ± "

[git_status]
conflicted = " ğŸ³ "
ahead = " ğŸğŸ’¨ "
behind =" ğŸ˜° "
diverged = " ğŸ˜µ "
untracked = " ğŸ¤·â€ "
stashed = " ğŸ“¦ "
modified = " ğŸ“ "
staged = '[++\($count\)](green)'
renamed = " ğŸ‘… "
deleted = " ğŸ—‘ "

[nodejs]
format = "via [ğŸ¤– $version](bold green) "
